Repository shchuko/ScratchedHologramFrom3D, pull requests merged in 2020-04, with the labels that each got.

#41 Feature/c svg data writer issue 34
  libs/File2DProcessingTools/include/CSvgFileWriter.hpp
  libs/File2DProcessingTools/include/CVectorGraphicsData.hpp
  libs/File2DProcessingTools/include/EFileAlreadyExistsException.hpp
  libs/File2DProcessingTools/include/EFileCannotBeOverwritten.hpp
  libs/File2DProcessingTools/include/IVectorGraphicsDataWriter.hpp
  libs/File2DProcessingTools/source/CSvgFileWriter.cpp
  libs/File2DProcessingTools/source/CVectorGraphicData.cpp
  libs/File2DProcessingTools/source/EFileAlreadyExistsException.cpp
  libs/File2DProcessingTools/source/EFileCannotBeOverwritten.cpp
  libs/File2DProcessingTools/test/CSvgFileWriterUnitTests.cpp
  libs/File2DProcessingTools/test/CVectorGraphicsDataUnitTests.cpp
  libs/File2DProcessingTools/test/EFileAlreadyExistsExceptionUnitTests.cpp
  libs/File2DProcessingTools/test/EFileCannotBeOverwrittenUnitTests.cpp
  test_resources/rhombus.svg
Labels: enhancement

#42 Add scratch hologram examples to readme.md
  .gitattributes
  README.md
  examples-pictures/scratch-holo-example.gif
Labels: documentation

#44 Feature/proj analyzer issue 32
  CMakeLists.txt
  ScratchedHologramFrom3DCLI/CMakeLists.txt
  include/CProjectionAnalyzer.hpp
  include/EWrongObjectsPosition.hpp
  source/CProjectionAnalyzer.cpp
  source/EWrongObjectsPosition.cpp
  test/CMakeLists.txt
  test/CProjectionAnalyzerUnitTests.cpp
  test/CProjectionBuilderUnitTests.cpp
  test/EWrongObjectPositionUnitTests.cpp
Labels: enhancement

#45 Feature/add write mul issue 43
  ScratchedHologramFrom3DCLI/main.cpp
  libs/File2DProcessingTools/include/CSvgFileWriter.hpp
  libs/File2DProcessingTools/include/IVectorGraphicsDataWriter.hpp
  libs/File2DProcessingTools/source/CSvgFileWriter.cpp
  libs/File2DProcessingTools/test/CSvgFileWriterUnitTests.cpp
  test_resources/rhombus-cube.svg
Labels: enhancement

#47 Add copy constructor to File3DProcessingTools::CObject3DData
  libs/File3DProcessingTools/include/CLinkedEdge.hpp
  libs/File3DProcessingTools/include/CObject3DData.hpp
  libs/File3DProcessingTools/source/CLinkedEdge.cpp
  libs/File3DProcessingTools/source/CObject3DData.cpp
  libs/File3DProcessingTools/test/CLinkedEdgeUnitTests.cpp
Labels: bug

#50 Feature/scratch math proj builder impl issue 35
  CMakeLists.txt
  include/CProjectionBuilder.hpp
  include/CScratchProjectionAnalyzer.hpp
  include/CScratchProjectionBuilder.hpp
  libs/File3DProcessingTools/include/CLinkedEdge.hpp
  libs/File3DProcessingTools/include/CObject3DData.hpp
  libs/File3DProcessingTools/source/CLinkedEdge.cpp
  libs/File3DProcessingTools/source/CObject3DData.cpp
  libs/File3DProcessingTools/test/CLinkedEdgeUnitTests.cpp
  libs/File3DProcessingTools/test/CObject3DDataUnitTests.cpp
  libs/Geometry3D/include/AVector3D.hpp
  libs/Geometry3D/include/CLinkedLine3D.hpp
  libs/Geometry3D/include/CLinkedVector3D.hpp
  libs/Geometry3D/include/CPoint3D.hpp
  libs/Geometry3D/include/CVector3D.hpp
  libs/Geometry3D/include/Geometry3DBase.hpp
  libs/Geometry3D/include/Geometry3DOperators.hpp
  libs/Geometry3D/source/AVector3D.cpp
  libs/Geometry3D/source/CLinkedLine3D.cpp
  libs/Geometry3D/source/CPoint3D.cpp
  libs/Geometry3D/source/Geometry3DOperators.cpp
  libs/Geometry3D/test/CPoint3DUnitTests.cpp
  source/CProjectionBuilder.cpp
  source/CScratchProjectionAnalyzer.cpp
  source/CScratchProjectionBuilder.cpp
  test/CProjectionBuilderUnitTests.cpp
  test/CScratchProjectionAnalyzerUnitTests.cpp
  test/CScratchProjectionBuilderUnitTests.cpp
Labels: bug, enhancement

#51 Feature/update i vector graphics data writer issue 49
  ScratchedHologramFrom3DCLI/main.cpp
  libs/File2DProcessingTools/include/CSvgFileWriter.hpp
  libs/File2DProcessingTools/include/IVectorGraphicsDataWriter.hpp
  libs/File2DProcessingTools/source/CSvgFileWriter.cpp
  libs/File2DProcessingTools/test/CSvgFileWriterUnitTests.cpp
  test_resources/rhombus-cube.svg
  test_resources/rhombus.svg
  test_resources/rhombus_template_center.svg
Labels: enhancement

#52 Feature/extend c vector graphics data interface issue 48
  ScratchedHologramFrom3DCLI/main.cpp
  libs/File2DProcessingTools/include/CSvgFileWriter.hpp
  libs/File2DProcessingTools/include/CVectorGraphicsData.hpp
  libs/File2DProcessingTools/include/ENotAColorHex.hpp
  libs/File2DProcessingTools/source/CSvgFileWriter.cpp
  libs/File2DProcessingTools/source/CVectorGraphicData.cpp
  libs/File2DProcessingTools/source/ENotAColorHex.cpp
  libs/File2DProcessingTools/test/CSvgFileWriterUnitTests.cpp
  libs/File2DProcessingTools/test/ENotAColorHexUnitTests.cpp
  test_resources/rhombus-cube.svg
  test_resources/rhombus.svg
  test_resources/rhombus_template_center.svg
  test_resources/test_color_width.svg
Labels: enhancement

#54 Bug fixes in CliTools library
  libs/CliTools/include/CArgsParser.hpp
  libs/CliTools/include/COption.hpp
  libs/CliTools/include/COptionBuilder.hpp
  libs/CliTools/source/CArgsParser.cpp
  libs/CliTools/source/COption.cpp
  libs/CliTools/source/COptionBuilder.cpp
  libs/CliTools/test/CArgsParserUnitTests.cpp
Labels: bug

#56 Close issue #55
  libs/CliTools/include/CArgsParser.hpp
  libs/CliTools/source/CArgsParser.cpp
  libs/CliTools/test/CArgsParserUnitTests.cpp
Labels: enhancement

#57 Close issue #33
  CMakeLists.txt
  include/CAppRunner.hpp
  libs/CliTools/include/CArgsParser.hpp
  libs/CliTools/source/CArgsParser.cpp
  libs/File2DProcessingTools/include/CVectorGraphicsData.hpp
  libs/File2DProcessingTools/source/CVectorGraphicData.cpp
  libs/File3DProcessingTools/include/CObjFileReader.hpp
  libs/File3DProcessingTools/include/EFile3DReadError.hpp
  libs/File3DProcessingTools/source/CObjFileReader.cpp
  libs/File3DProcessingTools/source/EFile3DReadError.cpp
  libs/File3DProcessingTools/test/CObjFileReaderUnitTests.cpp
  libs/File3DProcessingTools/test/EFile3DReadErrorUnitTests.cpp
  libs/ScratchProjectionMaths/include/CScratchProjectionBuilder.hpp
  libs/ScratchProjectionMaths/source/CScratchProjectionBuilder.cpp
  libs/ScratchProjectionMaths/test/CScratchProjectionBuilderUnitTests.cpp
  source/CAppRunner.cpp
  source/main.cpp
  test/CAppRunnerUnitTests.cpp
Labels: bug, enhancement

#60 Add checking negative values
  libs/CliTools/source/CArgsParser.cpp
  libs/CliTools/test/CArgsParserUnitTests.cpp
Labels: bug

#64 Bugfix/scratches printed out of svg canvas borders issue 58
  libs/CliTools/source/CArgsParser.cpp
  libs/File2DProcessingTools/include/CSvgFileWriter.hpp
  libs/File2DProcessingTools/include/IVectorGraphicsDataWriter.hpp
  libs/File2DProcessingTools/source/CSvgFileWriter.cpp
  test_resources/rhombus-cube.svg
  test_resources/rhombus_template_center.svg
  test_resources/test_color_width.svg
Labels: bug

#69 Close issue #67 - Add new cmake options
  CMakeLists.txt
  libs/CliTools/CMakeLists.txt
  libs/File2DProcessingTools/CMakeLists.txt
  libs/File3DProcessingTools/CMakeLists.txt
  libs/Geometry2D/CMakeLists.txt
  libs/Geometry3D/CMakeLists.txt
  libs/ScratchProjectionMaths/CMakeLists.txt
Labels: enhancement

#70 [issue #62] Add virtual ~IFile3DReader()
  libs/File3DProcessingTools/include/IFile3DReader.hpp
Labels: bug

#71 [issue #63] Add virtual ~IVectorGraphicsDataWriter()
  libs/File2DProcessingTools/include/IVectorGraphicsDataWriter.hpp
Labels: bug
