Repository shchuko/ScratchedHologramFrom3D, pull requests merged in 2020-03, with the labels that each got.

#14 Implement getPointBegin, getPointEnd, setPointBegin, setPointEnd in C…
  libs/Geometry3D/include/CLinkedVector3D.hpp
  libs/Geometry3D/source/CLinkedVector3D.cpp
  libs/Geometry3D/test/CLinkedVector3DTests.cpp
Labels: enhancement

#16 Feature/cli tools implement
  CMakeLists.txt
  ScratchedHologramFrom3DCLI/CMakeLists.txt
  ScratchedHologramFrom3DCLI/main.cpp
  libs/CLITools/CMakeLists.txt
  libs/CLITools/include/CArgsParser.hpp
  libs/CLITools/source/CArgsParser.cpp
  libs/CLITools/test/CArgsParserUnitTests.cpp
  libs/CLITools/test/CMakeLists.txt
  libs/CliTools/CMakeLists.txt
  libs/CliTools/include/CArgsParser.hpp
  libs/CliTools/include/COption.hpp
  libs/CliTools/include/COptionBuilder.hpp
  libs/CliTools/include/EOptionBuildError.hpp
  libs/CliTools/include/EOptionNotPresentInDictionary.hpp
  libs/CliTools/include/EParserError.hpp
  libs/CliTools/include/ERequiredOptionNotPresent.hpp
  libs/CliTools/include/EUnrecognizedOptionParsed.hpp
  libs/CliTools/include/EValuedOptionWithoutValue.hpp
  libs/CliTools/source/CArgsParser.cpp
  libs/CliTools/source/COption.cpp
  libs/CliTools/source/COptionBuilder.cpp
  libs/CliTools/source/EOptionBuildError.cpp
  libs/CliTools/source/EOptionNotPresentInDictionary.cpp
  libs/CliTools/source/EParserError.cpp
  libs/CliTools/source/ERequiredOptionNotPresent.cpp
  libs/CliTools/source/EUnrecognizedOptionParsed.cpp
  libs/CliTools/source/EValuedOptionWithoutValue.cpp
  libs/CliTools/test/CArgsParserUnitTests.cpp
  libs/CliTools/test/CMakeLists.txt
  libs/CliTools/test/COptionCOptionBuilderUnitTests.cpp
  libs/CliTools/test/EOptionBuildErrorUnitTests.cpp
  libs/CliTools/test/EOptionNotPresentInDictionaryUnitTests.cpp
  libs/CliTools/test/EParserErrorUnitTests.cpp
  libs/CliTools/test/ERequiredOptionNotPresentUnitTests.cpp
  libs/CliTools/test/EUnrecognizedOptionParsedUnitTests.cpp
  libs/CliTools/test/EValuedOptionWithoutValueUnitTests.cpp
Labels: enhancement

#17 Implement CLinkedLine3D.
  libs/Geometry3D/include/CLinkedLine3D.hpp
  libs/Geometry3D/source/CLinkedLine3D.cpp
  libs/Geometry3D/test/CLinkedLine3DUnitTests.cpp
Labels: enhancement

#19 Add calculation epsilon to CLinkedLine3DUnitTests equal-double checks
  libs/Geometry3D/test/CLinkedLine3DUnitTests.cpp
Labels: bug

#21 Add calculation epsilon to CLinkedLine3DUnitTests equal-double checks
  libs/Geometry3D/test/CLinkedLine3DUnitTests.cpp
Labels: bug

#23 Feature/geometry 3d add equals operators issue 22
  libs/Geometry3D/include/CPoint3D.hpp
  libs/Geometry3D/include/Geometry3DOperators.hpp
  libs/Geometry3D/source/CPoint3D.cpp
  libs/Geometry3D/source/Geometry3DOperators.cpp
  libs/Geometry3D/test/Geometry3DOperatorsLibTests.cpp
Labels: bug, documentation, enhancement

#25 Bugfix/linked line is point on line fix issue 24
  libs/Geometry3D/include/AVector3D.hpp
  libs/Geometry3D/source/CLinkedLine3D.cpp
  libs/Geometry3D/test/CLinkedLine3DUnitTests.cpp
Labels: bug, documentation

#27 Feature/resolve issue 26
  libs/Geometry3D/include/CPoint3D.hpp
  libs/Geometry3D/include/CVector3D.hpp
  libs/Geometry3D/source/CPoint3D.cpp
  libs/Geometry3D/source/CVector3D.cpp
  libs/Geometry3D/test/CPoint3DUnitTests.cpp
  libs/Geometry3D/test/CVector3DUnitTests.cpp
Labels: enhancement

#28 Feature/f3d pt impl issue 13
  .appveyor.yml
  .gitattributes
  .travis.yml
  CMakeLists.txt
  libs/File3DProcessingTools/CMakeLists.txt
  libs/File3DProcessingTools/include/CLinkedEdge.hpp
  libs/File3DProcessingTools/include/CObjFileReader.hpp
  libs/File3DProcessingTools/include/CObject3DData.hpp
  libs/File3DProcessingTools/include/CPoints3DStatistics.hpp
  libs/File3DProcessingTools/include/CPolygon.hpp
  libs/File3DProcessingTools/include/EFile3DReadError.hpp
  libs/File3DProcessingTools/include/FOperators.hpp
  libs/File3DProcessingTools/include/IFile3DReader.hpp
  libs/File3DProcessingTools/include/TFile3DProcessingToolsTypes.hpp
  libs/File3DProcessingTools/source/CLinkedEdge.cpp
  libs/File3DProcessingTools/source/CObjFileReader.cpp
  libs/File3DProcessingTools/source/CObject3DData.cpp
  libs/File3DProcessingTools/source/CPoints3DStatistics.cpp
  libs/File3DProcessingTools/source/CPolygon.cpp
  libs/File3DProcessingTools/source/EFile3DReadError.cpp
  libs/File3DProcessingTools/test/CLinkedEdgeUnitTests.cpp
  libs/File3DProcessingTools/test/CMakeLists.txt
  libs/File3DProcessingTools/test/CObjFileReaderUnitTests.cpp
  libs/File3DProcessingTools/test/CObject3DDataUnitTests.cpp
  libs/File3DProcessingTools/test/CPoints3DStatisticsUnitTests.cpp
  libs/File3DProcessingTools/test/CPolygonUnitTests.cpp
  libs/File3DProcessingTools/test/EFile3DReadErrorUnitTests.cpp
  test_resources/cube.obj
  test_resources/unsupported.obj
Labels: enhancement

#30 README.md budges fixes
  README.md
Labels: bug

#39 Feature/issue 37
  libs/Geometry2D/include/AVector2D.hpp
  libs/Geometry2D/include/CLineSegment2D.hpp
  libs/Geometry2D/include/CPoint2D.hpp
  libs/Geometry2D/include/CVector2D.hpp
  libs/Geometry2D/source/CLineSegment2D.cpp
  libs/Geometry2D/source/CPoint2D.cpp
  libs/Geometry2D/source/CVector2D.cpp
Labels: enhancement

#40 Feature/c vector graphics data issue 31
  libs/File2DProcessingTools/CMakeLists.txt
  libs/File2DProcessingTools/include/CVectorGraphicsData.hpp
  libs/File2DProcessingTools/source/CVectorGraphicData.cpp
  libs/File2DProcessingTools/test/CMakeLists.txt
  libs/File2DProcessingTools/test/CVectorGraphicsDataUnitTests.cpp
Labels: enhancement
